apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-proxy
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  webproxy: true
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  accessPolicy:
    inbound:
      rules:
        - application: omsorgspenger-journalforing
          namespace: omsorgspenger
          cluster: {{clusterGcp}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  envFrom:
    - secret: omsorgspenger-proxy-srvusercredentials
    - secret: ldap-credentials
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
