name: Bygg og deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Bygge JAR
        run: ./gradlew test shadowjar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sett tag for docker
        run: echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg & last opp Docker image
        run: |
          docker build --pull --tag ${BASE_IMAGE}:${TAG} --tag ${BASE_IMAGE}:latest .
          docker push ${BASE_IMAGE} --all-tags

      - name: Sett image for nais deploy
        run: echo "IMAGE=${BASE_IMAGE}:${TAG}" >> $GITHUB_ENV

      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yaml
          VARS: nais/dev-fss.json

      - name: Deploy til prod-fss
        if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'ci skip')
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/naiserator.yaml
          VARS: nais/prod-fss.json
